### ISSUE TITLE
fip api change

### ISSUE THREAD

**Issue by fiplistener** [mattberjon/fip#164]
Sometime this week the fip api completely changed. The URLs are in a new format, example:

https://www.fip.fr/latest/api/graphql?operationName=Now&variables={%22bannerPreset%22%3A%22600x600-noTransform%22%2C%22stationId%22%3A7%2C%22previousTrackLimit%22%3A3}&extensions={%22persistedQuery%22%3A{%22version%22%3A1%2C%22sha256Hash%22%3A%228a931c7d177ff69709a79f4c213bd2403f0c11836c560bc22da55628d8100df8%22}}

Since then I've been unable to pull track data from fip using this script. Even though the output looks the same simply changing to the new URL hasn't been enough to get it to work again.

**Comment by mattberjon** [comment]
Hi @fiplistener,

Thanks for the issue you raised. Sorry I didn't get back in touch earlier. I adapted the code according to URL you gave and added the possibility to fetch the n-1 occurence on previous songs played.

I considered this issue as closed.
